### PR TITLE
i18n(pl-PL): Add Polish translation

### PR DESCRIPTION
**Pull request by SirRFI**
Added Polish translation.

launcher
workspaces
applications

Related:
https://github.com/pop-os/pop/issues/1975
https://github.com/pop-os/desktop-widget/pull/70

### CODE REVIEW

**Comment by SirRFI** [comment]
I suggest to sort translation languages alphabetically (case insensitive ascending).

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
For some reason, I'm not seeing this applied in a user account set to Polish:
Zrzut ekranu z 2021-11-17 10-09-15
However, the issue doesn't seem to be with this PR; existing translations such as Spanish also aren't showing up for these icons, with the master branch or this branch. It's working in @SirRFI's screenshots, so I need to figure out what's going on with my test machine.

**Comment by SirRFI** [comment]
@jacobgkau I tested it by changing the language via GUI then relogging (reboot not needed). I see the date-time is not affected either.

**Comment by jacobgkau** [comment]
> @jacobgkau I tested it by changing the language via GUI then relogging (reboot not needed). I see the date-time is not affected either.

Good catch on the date/time. That one is controlled by the Formats setting under Region & Language, which doesn't seem to have an effect on the dock icons.

I'm going to be reinstalling a few times to test some installer work, so I'll come back to this either on a fresh install or on a different machine, if nobody else gets to it first.

**Comment by jacobgkau** [comment]
This starts working if I change the key from `Name[pl_PL]=` to `Name[pl]=`.

This affects Spanish as well, but not Portuguese (the `pt_BR` translation shows in a `pt_BR` user, just not a `pt_PT` user.)

The [FreeDesktop spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html) suggests this should not be happening (if the key uses `lang_COUNTRY`, then `lang` by itself should be considered), but that doesn't match what I'm seeing happen.

**Comment by SirRFI** [comment]
> Good catch on the date/time. That one is controlled by the Formats setting under Region & Language, which doesn't seem to have an effect on the dock icons.

I know. I mentioned it because I recall both changing, though I am unsure if it was PopOS or Fedora.


I updated the system and reswapped languages:

image



Just when I was about to say it works, I managed to break it. Now I am experiencing same issue as you - the translation does not work anymore, despite system language is is Polish where it can be. I think it happened after I changed language order in left dialog, as so far I've been using the one on the right.

image

Here's potential culprit:
```$ env | grep pl
LANGUAGE=pl:en_US:en
LC_ADDRESS=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_MONETARY=pl_PL.UTF-8
LC_PAPER=pl_PL.UTF-8
LANG=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_NUMERIC=pl_PL.UTF-8
```
~~I tried forcing `pl_PL` in `LANGUAGE`, but nothing changed.~~ **EDIT:** It actually does - see next comment.



Looks like a bug to me. How did you create Polish user? I think I selected the language in installer. By the way, "polski" appears somewhere on bottom in the installer, far below other "p" languages for some reasons. Is it not sorted alphabetically, or is case sensitive?

**Comment by SirRFI** [comment]
I managed to recreate the problem. Installing fresh PopOS using Polish language in installer, creates `LANGUAGE=pl_PL`, with no other locale envs. Switching language in GUI adds more env variables and changes `LANGUAGE` env to `pl:en_US:en`.

For testing purposes, I edited `~/.bashrc` by adding `export LANGUAGE=pl_PL.UTF-8` (and later `export LANGUAGE=pl_PL`) and it fixed the issue. I relogged between every test for the envs to be reloaded. As soon I commented that line out, these 3 translations broke.

I actually tried this before, but maybe the files were overwritten by some update, I don't know. 

---

More details on testing steps I took:

0. I removed existing VM and redownloaded the beta ISO (`pop-os_21.10_amd64_intel_2.iso`).
1. Selected Polish language in installer. As previously mentioned, for whatever reason it's far below other languages starting on "P" - I suspect it's case sensitive listing. Where can I report this? Also this installer could use some search mechanism.

popos-installer1
popos-installer2

2. Didn't do any updates etc. Checked the translations by hovering over the icons in dock - English.
3. Edited the 3 files to add `pl_PL` translations as in initial commit. Saved and checked - still English, though it self-refreshed soon after with translation.
4. Log out and log in - translation works.
5. Reboot - translation works.
6. `sudo apt update` and `sudo apt upgrade`. Update overwrote the files, so I had to edit them again to make it work.
7. Just to be sure I switched to en_US via GUI, logged out, logged in, then switched back to Polish and relogged - and this is where it broke.
8. Experimented with env variables in `~/.bashrc` as explained in summary on the top.

**Pull request closed without merging**
