### PR TITLE
Applications Popup Improvements

### PR DESCRIPTION
**Pull request by ids1024**
Addressees some of the points in https://github.com/pop-os/cosmic/issues/228.

* Dialogs now have a minimum width, and are formatted with a title and description.
* Empty folder titles are displayed as "Untitled"
  - Would it be good if this is somehow distinct from that actual text? Not that anyone would probably want to label it that.
* Center folder icon box
* Remove dot in app icon, which doesn't really fit here
* Things like notifications now appear over the Applications popup, not under
* PageUp/PageDown to change folder
* Update 'checked' state of Applications button based on whether popup is open 
* Search
  -  There is now a timeout for shop search results, like stock Gnome Shell; seems to help a bit
     * I think the performance should match what it was before; not sure if the code in Pop Shop could be improved too
     * Does not delay local app search
   - Formatted like mockup with "Available to Install" label
   - Spinner indicates shop results are loading

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
These improvements are good. One strange thing I noticed, that is not a regression, is that the Launcher can be opened on top of the applications library.

**Comment by 13r0ck** [comment]
# Bugs
It is possible to break the tabl/PgUp/PgDn by pressing the the following compination of keys
```
Super+A
PgDn
PgUp
PgUp
PgUp
Tab
PgDn
```
Then PgUp/PgDn/Tab will do nothing. The key presses don't break it every time ~50% of the time.
I think it has to do with over/under indexing the folder values maybe. I also got the issue by pressing PgDn too many times, but that was less reliable.

https://user-images.githubusercontent.com/58987761/142259704-3ac0faed-297d-40f5-8a4b-6126c91ee83a.mp4

# Subjective Bugs
> These arn't bugs but feel weird to me at least. Feel free to ignore if nobody else agrees.
<details>
    <summary>"Available to Install" isn't centered. I also feel like this section should have a slightly different background color to separate it a bit more from the local search results.</summary>
<br>

Screenshot from 2021-11-17 11-02-20</summary>

</details>
<details>
    <summary>Text in the "rename" and "new" folder dialogs isn't centered.</summary>
<br>

Screenshot from 2021-11-17 10-48-37

</details>
<details>
    <summary>When a folder as a *really* long name an ellipsis is appended in the folder icon, but not in the folder title.</summary>
<br>

Screenshot from 2021-11-17 10-49-28

</details>
<details>
    <summary>Naming a folder with just spaces still looks empty.</summary>
<br>

Screenshot from 2021-11-17 10-59-05

</details>
<details>
    <summary>Inserting spaces into the folder name can offset the text. (I think leading and trailing spaces should be trimmed.)</summary>
<br>

Screenshot from 2021-11-17 11-00-35

</details>
* When renaming a folder/creating a folder pressing enter doesn't submit the changed name

# Checklist
Addressees some of the points in https://github.com/pop-os/cosmic/issues/228.

* ~~Dialogs now have a minimum width, and are formatted with a title and description.~~
* ~~Empty folder titles are displayed as "Untitled"~~
  - ~~Would it be good if this is somehow distinct from that actual text? Not that anyone would probably want to label it that.~~ (I think its good the way that it is)
* ~~Center folder icon box~~
* ~~Remove dot in app icon, which doesn't really fit here~~
* ~~Things like notifications now appear over the Applications popup, not under~~
* ~~PageUp/PageDown to change folder~~
* ~~Update 'checked' state of Applications button based on whether popup is open~~
* Search
  -  ~~There is now a timeout for shop search results, like stock Gnome Shell; seems to help a bit~~
     * ~~I think the performance should match what it was before; not sure if the code in Pop Shop could be improved too~~
     * ~~Does not delay local app search~~
   - ~~Formatted like mockup with "Available to Install" label~~
   - ~~Spinner indicates shop results are loading~~

**Comment by ids1024** [comment]
> It is possible to break the tabl/PgUp/PgDn by pressing the the following compination of keys

Interesting. Trying to do that, either quickly pressing keys or slowing, I can't seem to reproduce it.

> "Available to Install" isn't centered. I also feel like this section should have a slightly different background color to separate it a bit more from the local search results.
> Text in the "rename" and "new" folder dialogs isn't centered.

Easy enough to adjust if that's what we want, but I based it on https://github.com/pop-os/cosmic/issues/228#issuecomment-965790621.

> When a folder as a *really* long name an ellipsis is appended in the folder icon, but not in the folder title.

Not a big deal really, but it might as well ellipsize there as well. Hopefully no one actually wants a title like that. Though I actually do see an elipsis when it's multiple words (I think pango has multiple modes for this). Though it overlaps buttons due to how its currently implemented:

Screenshot from 2021-11-17 11-52-21

> Naming a folder with just spaces still looks empty.
> Inserting spaces into the folder name can offset the text. (I think leading and trailing spaces should be trimmed.)

So, make folder creation/rename automatically trim whitespace from both ends of the name? I guess that makes sense since someone may accidentally add space, and probably would never want it.

> When renaming a folder/creating a folder pressing enter doesn't submit the changed name 

Come to think of it, the dialog API in Gnome Shell has a way to bind keys to buttons, which would probably work here.

**Comment by 13r0ck** [comment]
> Interesting. Trying to do that, either quickly pressing keys or slowing, I can't seem to reproduce it.

I can get it to reporduce on a few machine. Just try pressing PgUp and PgDn and tab a bunch with an emphasis on pressing PgUp several times while already on the `Library Home`

> Easy enough to adjust if that's what we want, but I based it on #228 (comment).

Ah I missed that. All good then!

> Not a big deal really, but it might as well ellipsize there as well. Hopefully no one actually wants a title like that. Though I actually do see an elipsis when it's multiple words (I think pango has multiple modes for this). Though it overlaps buttons due to how its currently implemented:

I agree. It really doesn't matter much, If adding the ellipsis makes it overlap, then I don't think it is worth it.

**Comment by ids1024** [comment]
Okay, I see it just mashing PageUp/PageDown/Tab, if not consistently. Interestingly Esc is also not working in that state, so the key event handler that also handles that isn't running/working.

**Comment by 13r0ck** [comment]
The PageUp/PageDown/Tab bug is still present

**Comment by 13r0ck** [comment]
Defaulting to enter does work :+1:

**Comment by ids1024** [comment]
I'm not sure what's going on with the pageup/pagedown/tab issue, though I have some ideas to debug it. I guess a different actor is probably getting keyboard focus, though I'm not sure why...

**Comment by 13r0ck** [comment]
If you would like I am fine approving this and creating a separate issue for the pageup/pagedown/tab issue?

**Comment by ids1024** [comment]
Sounds good, if the issue doesn't seem too critical. I can only seem to trigger it with keyboard mashing that wouldn't be likely in actual use.

Switching between home and other folders switches keyboard focus between the `ClutterText` of the search and the `CosmicAppsHeader` that appears in its place for folders, while tab selects a `CosmicAppIcon`. Somehow rapidly hitting these keys causes the toplevel `global.stage` to receive key focus (the default). It's not obvious exactly why/how that ends up happening.

**Review by 13r0ck — APPROVED** [review]
This PR makes all of its required improvements. There is one bug created, but for the sake of pushing the other fixes I am approving this and opening issue #250 for the last remaining bug.

**Pull request merged**
