### PR TITLE
Add preferences screen with link to Settings

### PR DESCRIPTION
**Pull request by ids1024**
As suggested in comment on https://github.com/pop-os/desktop/issues/61.

Screenshot from 2021-06-01 12-03-42

### CODE REVIEW

**Comment by jacobgkau** [comment]
Since users were accessing Extensions to try and configure the dock, would we also want to do this for https://github.com/pop-os/gnome-shell-extension-ubuntu-dock?

**Comment by ids1024** [comment]
Probably. Opened https://github.com/pop-os/gnome-shell-extension-ubuntu-dock/pull/12 with the exact same preferences screen.

**Comment by jacobgkau** [comment]
We seem to style Cosmic as COSMIC in most places, should it be all-caps within this sentence?

**Comment by ids1024** [comment]
Ah right, I suppose it should be formatted as "COSMIC".

@maria-komarova Any thoughts on this? The message and button with this text, centered, is basically the first thing that came to mind, but maybe something else could be better.

**Comment by jacobgkau** [comment]
Fwiw, I think the button looks great, my only thought is that the dock PR might want to say "The dock is configured in Settings." instead of referring to COSMIC in that one, or at least "The COSMIC dock is configured in Settings." to clarify that they're looking at the dock settings and didn't click the wrong button or something. But Maria should of course chime in as well.

**Comment by maria-komarova** [comment]
Could you remind me how one would get to this window exactly? Go to the extensions and then click on the configuration icon? 

For the copy, I wonder if something like that would be better: 
image
We might need to space the button further from the copy for a more polished look (24px on that mockup on the screenshot, 2x the usual GNOME spacing). 
We also have a COSMIC logo if we want to provide that as well (the one used on the wallpaper).

**Comment by maria-komarova** [comment]
Here it is with the logo is we want it: 
image
We'll have to have a logo for the light mode and the logo the dark mode. We have both assets, would just need to use one or the other contingent on the appearance.

**Comment by maria-komarova** [comment]
Here are the two logos, in case we decide to use them. Dark logo is for the light mode, bright - for the dark mode. Bright is not quite visible on white background but it is attached here. 
COSMIC_logo_dark
COSMIC_logo_bright

**Comment by ids1024** [comment]
I quite like the version with the logo. Though I guess the icon would need to be available to either cosmic or the dock package, and Gtk lacks any simple and reliable way to check if the current theme is a dark theme (dark themes aren't really that well supported in Gtk)...

**Comment by maria-komarova** [comment]
It's fine even without the logo, as much as I like it. Even just a copy and button would work.

**Comment by ids1024** [comment]
Anyway, updated the text and added more spacing between the label and the button:

Screenshot from 2021-06-02 10-05-27

**Review by jacobgkau — APPROVED** [review]
A shame we can't use the logo, but it looks good anyway.

Can we get another PR on https://github.com/pop-os/gnome-shell-extension-ubuntu-dock to make it match? (https://github.com/pop-os/gnome-shell-extension-ubuntu-dock/pull/12 was merged too early.)

**Comment by mmstick** [comment]
I think we can render an offscreen window and then fetch a pixel on that window and evaluate whether it's dark or light. I feel like I've seen that done somewhere before in GTK. (besides checking if the GTK theme has dark in the name)

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
