### PR TITLE
fix: Correct behavior on closing applications

### LINKED ISSUE #92: App grid showing behind Workspaces overview
I'm assuming this was caused by https://github.com/pop-os/cosmic/pull/90.

On 702d7da, there's a case where the Applications grid shows up behind the window spread in the Workspaces overview:

Screenshot from 2021-06-25 09-36-52

This happens after opening and closing the Applications menu by clicking the icon in the dock twice, then opening the Workspaces menu. It stops happening after navigating from the Applications menu to the Workspaces menu by clicking the menu item in the top left of the screen.

I've also had a case where Workspaces view didn't show my windows:

rect839

I haven't been able to recreate this one yet, but I'm assuming they're both related to GNOME Shell not knowing which page is supposed to be active.

### PR DESCRIPTION
**Pull request by ids1024**
This seems to fix the same problems as the previous version, but without breaking some of Gnome Shell's own logic.

Fixes https://github.com/pop-os/cosmic/issues/92.

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
On 374ce6d, I cannot exit from the Applications or Workspaces menus. I also cannot switch between those two menus directly.

**Comment by ids1024** [comment]
Hm, strange. It behaves normally for me.

**Comment by jacobgkau** [comment]
I was testing on the darp7 before. I've recreated the issue on galp5 set to NVIDIA mode, as well as an oryp7 that did not have any other staging repositories added.

Here's journalctl output when I try to exit Workspaces:
```
Jun 25 12:49:49 pop-os gnome-shell[2212]: JS ERROR: ReferenceError: showAppsButton is not defined
                                          enable/<@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/extension.js:333:9
                                          _animateNotVisible@resource:///org/gnome/shell/ui/overview.js:646:27
                                          hide@resource:///org/gnome/shell/ui/overview.js:635:14
                                          overview_hide@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/overview.js:70:23
                                          overview_toggle@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/overview.js:78:22
                                          toggle@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/topBarButton.js:66:24
                                          vfunc_event@/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/topBarButton.js:106:22
```

**Comment by ids1024** [comment]
Ah, I had that variable defined in an earlier version of this. Though I though I tested the version in the PR...

Anyway, should be fixed.

**Review by jacobgkau — APPROVED** [review]
- [X] Open and close Applications with dock
- [X] Open and close Workspaces with dock
- [X] Open and close Applications with top bar
- [X] Open and close Workspaces with top bar
- [X] Open and close Applications with keyboard
- [X] Open and close Workspaces with keyboard
- [X] Open Applications with dock, switch to Workspaces with top bar, exit Workspaces with top bar.
- [X] Open Applications with top bar, switch to Workspaces with top bar, exit Workspaces with dock.
- [X] Open Workspaces with dock, switch to Applications with top bar, exit Applications with top bar.
- [X] Open Workspaces with top bar, switch to Applications with top bar, exit Applications with dock.
- [X] Able to launch apps with Applications and move/switch windows with Workspaces.
- [X] Perform all of those tasks again with windows open on an external display, no graphical glitches.

The one thing I noticed is that after opening/closing Workspaces, the window overview animation is slightly glitched the next time Applications is opened (but not subsequent times):
https://user-images.githubusercontent.com/7199422/123476711-4f89db00-d5ba-11eb-934d-128bffad842c.mp4

This appears to be caused by the workspace slider (correctly) not showing up when Applications is opened. In any case, that's much less critical than the issues this is fixing.

**Comment by bflanagin** [comment]
The exiting Workspaces and Applications menus issue is gone, and the application grid  is no longer showing behind the windows in Workspace view.

**Pull request merged**
