### PR TITLE
feat: Do not change additional monitors when opening 'Applications'

### PR DESCRIPTION
**Pull request by ids1024**
Also requires a `cosmic-dock` change to prevent opening 'Applications' from making the dock appear on additional monitors. Though I'm not entirely sure what behavior we want for that.

https://github.com/pop-os/gnome-shell/issues/70

Leaving this as a draft for now since the workspace switcher doesn't seem to load correctly opening Applications then switching to Workspaces. As far as I can tell it's working perfectly other than that.

### CODE REVIEW

**Comment by ids1024** [comment]
> the workspace switcher doesn't seem to load correctly opening Applications then switching to Workspaces.

Actually, that seems to be unrelated: https://github.com/pop-os/cosmic/pull/117.

Though switching from "Workspaces" to "Applications" seems to not move windows back to their previous positions. While moving the `Main.overview.viewSelector._workspacesDisplay._workspacesViews.forEach` loop to the start of the callback brings back the issue with the wallpaper briefly flashing opening/closing "Applications". Hm.

**Comment by ids1024** [comment]
Rebasing this, it seems to work properly now as far as I can tell. I don't know if we want to merge this sort of thing now.

**Review by jackpot51 — APPROVED** [review]

**Comment by bflanagin** [comment]
I'm not seeing any change in behavior with this PR applied. Is this just the first part of a larger change? If so regression tests are going well and I can finish them up an approve. If not then what is it supposed to do, and how do I make it do it?

**Comment by bflanagin** [comment]
Update: Levi ran the same tests on another laptop and it behaves as expected (that is the way that I thought it would work.) Will try to determine why it doesn't work mine the same way.

**Comment by ids1024** [comment]
> If not then what is it supposed to do, and how do I make it do it?

This changes the behavior of the Applications view on systems with multiple monitors.

Prior to this change, the Applications button opened the applications view on the primary monitor, while on all other monitors it looks the same as the workspaces view.

With this, and https://github.com/pop-os/cosmic-dock/pull/39 to change the behavior of the dock, clicking the Applications button should result in no visual change on additional monitors. It also overrides mouse input handling on additional monitors so that hovering has no effect and clicking anywhere closes the Applications view (kind of like the launcher).

**Comment by ids1024** [comment]
Earlier I had this PR as a draft because it wasn't working quite properly, and because I'm not sure how much we want to change behavior mid-release. But it seems to be working properly now (as noted in my earlier comment, after rebasing).

I guess there's not really an issue with this since the prior behavior isn't particularly useful.

**Comment by bflanagin** [comment]
I found the setting that breaks the behavior. If the user has "Workspaces on Primary Display Only" selected the second displays windows will still shift around as they did before the fix.

**Comment by ids1024** [comment]
Interesting. I wonder why that makes a difference.

Edit: Okay, it produces JavaScript errors.

**Comment by ids1024** [comment]
Pushed a change that seems like it should work, but doesn't quite. It fixes the error, but for some reason it only works with Workspaces on Primary Only when switching Workspaces to Applications, but not when opening Applications directly.

**Comment by ids1024** [comment]
Now it's working except an issue with the animation from Workspaces to Applications. Looking for a solution for that...

**Comment by ids1024** [comment]
I've changed the implementation to a cleaner solution that doesn't need to override `animateToOverview`. I think this version is less likely to have issues.

This changes the behavior on additional monitors when switching between Applications and Workspaces to a fade rather than a zoom. Perhaps that's better anyway.

It seems to work now.

**Review by bflanagin — APPROVED** [review]
Works as expected.
No regressions found.

**Pull request merged**
