### PR TITLE
WIP: rust mutter plugin

### PR DESCRIPTION
**Pull request by jackpot51**
Extremely WIP, internal use only

### CODE REVIEW

**Comment by ids1024** [comment]
This doesn't seem to currently be building with Rust 1.51, due to gtk-rs-core/gtk3-rs requiring a featuring that it doesn't have. That seems to be addressed by updating `Cargo.lock` to use gtk-rs-core `9c1fbadd16ed346c66ea1ef3a990e411f6c35eb2` and gtk3-rs `2f15a15e933b93f1f644ddbb7bb0b0e0f7492b12`. (The last commits that seem to work with 1.51.)

**Comment by jackpot51** [comment]
@ids1024 feel free to commit with those revisions locked

**Comment by ids1024** [comment]
Added a commit subclassing from Rust instead of using C code, by implementing `IsSubclassable` in `mutter-rs`.

**Comment by ids1024** [comment]
Ah, it looks like using gtk here causes `XDG_SESSION_TYPE=wayland pop-cosmic` to deadlock, since gtk tries to connect to the compositor, which is running in the same process. It may be necessary to avoid using gtk in the same process.

**Comment by ids1024** [comment]
Pushed a commit preventing the deadlock on Wayland. It's a bit of a hack, but no more than gnome-shell, and trying to add the  `linicon` crate instead resulted in an error building a dependency.

**Comment by jackpot51** [comment]
Replaced by cosmic-comp

**Pull request closed without merging**
