### PR TITLE
Adress main remaining App Library concerns

### PR DESCRIPTION
**Pull request by ids1024**
* Correctly show newly installed app
* Styling for folder rename/delete buttons (both light and dark)
* Update colors in light theme
* Correctly close Applications clicking "Show Applications" in dock
  - Also requires https://github.com/pop-os/cosmic-dock/pull/91
* Select first result in search, with similar behavior to stock Gnome

### CODE REVIEW

**Comment by jacobgkau** [comment]
All of the improvements listed are looking good.

I noticed that the Launcher closes the App Library, but the App Library doesn't close the Launcher (I thought I saw this mentioned a while back, but I don't see it in https://github.com/pop-os/cosmic/issues/228):

Screenshot from 2021-12-07 12-44-33

The Launcher stays on top, but the App Library takes focus. it seems like the Launcher should close when the App Library is opened. Would that be done in COSMIC or in Pop Shell?

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Found one regression: I can no longer navigate through app icons using the arrow keys. Focus just stays in the search box (Tab doesn't seem to change focus, either.)

**Comment by ids1024** [comment]
Ah right, it should intercept those key presses only while in a search.

Should be fixed now.

**Review by jacobgkau — APPROVED** [review]
The regression has been fixed. All features from this and the previous three App Library PRs are still working.

**Review by jackpot51 — APPROVED** [review]

**Comment by lhotari** [comment]
@jackpot51 is it possible that this change could cause this issue: https://github.com/pop-os/beta/issues/333 ?

**Pull request merged**
