### PR TITLE
Applications popup

### PR DESCRIPTION
**Pull request by ids1024**
Implementation of https://github.com/pop-os/cosmic/issues/207.

I think the main issues here are addressed now, but it still needs support for editing folders, and various smaller fixes.

Currently working:
* Open on current monitor, centered, closing open escape key or click outside popup
* Search
* Scrolling through list of apps
* Drag and drop from popup to dock
* Lists folders, which filter the list of applications

Still need to implement/fix:
* Folder editing (creation, deletion, rename, drag app to folder)
* Update correctly when app installed, etc.
* Pop Shop search results not correctly working for some reason
* Funny spacing when first opened, which for some reason isn't an issue after that
* Various style improvements

### CODE REVIEW

**Comment by jackpot51** [comment]
@ids1024 I don't think folders that are categories are working

```
[org/gnome/desktop/app-folders/folders/Games]
categories=['Game']
name='Games'
translate=false
```

**Comment by ids1024** [comment]
Ah right. It will need some logic to handle that. Getting a list of apps in a category isn't that hard though, so that shouldn't be a huge challenge.

**Comment by ids1024** [comment]
This is now mostly working, including creating/renaming/deleting folders, and dragging apps to folders. For some reason there's a delay dragging from one folder to another, I think that's probably blocking on some of the default Gnome Shell Applications code, which still exists even if we're not using it...

There are still bugs and style issues to work out, and some smaller things. The hardest part here is dealing with the limitations of Clutter/St, since toolkit feature Gnome Shell doesn't use are largely absent or buggy.

**Comment by jackpot51** [comment]
Category folders aren't working yet

**Comment by ids1024** [comment]
Hm, I have some code that should display category folders correctly, but for some reason it produces "Attempting to run a JS callback during garbage collection." errors calling `appInfo.get_id()`...

**Comment by ids1024** [comment]
Still not sure what those errors are about, but it wasn't working since I used `for...in` instead of `for...of`. There's now basic support for category folders. Probably also want to update `excluded-apps` when adding/removing an app from a category folder like Gnome Shell does. (Category folders in Gnome Shell seem a bit strange; not sure the way that works is at all clear to the user, but I'd have to try using stock Gnome more.

**Comment by WatchMkr** [comment]
- Only three rows of application icons before the list scrolls
- Reduce icon size by 20%
- No folder title, edit, or delete button on the Home screen
- Reduce folder size by 50%
- Center folders
- Reduce the search bar length by 50% and center.
- Increase pop-up width by 10%
- Remove search in folders (only in Home)
- Center folder title and increase font size

**Comment by maria-komarova** [comment]
In addition to previous comments, looks like the delete and edit buttons are present in the home folder - they should only be available in other folders but not in the home folder.

**Comment by maria-komarova** [comment]
To expand on the mockups, here are some spacing and sizing details. 
The app icons in the app-library are currently at 72px. Below are more exact sizes from the mockups. The corner radius in Figma sometimes differs from Shell so that one might need to be refined more later. 
app-icon

Here are the sizes for folder icons:
folder-icon

Spacing between rows of icons on the mockups is 48px. The width of the search bar is 460. 
Padding on right and left of the grid of app icons is 56px. Padding on top of the search bar is 36px, same 36px between search bar and app icons. At the bottom, spacing from app icons to the divider is 18px, same 18px above and below the folder icons in the bottom part.

**Comment by jackpot51** [comment]
In addition to what @WatchMkr and @maria-komarova said, the folders should probably scroll horizontally if they exceed the width of the application library

**Comment by maria-komarova** [comment]
The idea was to have maximum of 2 rows of folder icons actually. And then start scaling the icons down. Here is a mockup from Figma. 
Multiple-folders

**Comment by ids1024** [comment]
Hm, I wonder home many folders someone would reasonably use. That design would become awkward with too many. Though I guess any would in one way or another.

**Comment by maria-komarova** [comment]
Yeah, that's what I wonder about as well. But then horizontal scroll on top of the vertical one might be a bit too much too. Rows and scaling would at least keep folders in view. I wonder how many folders people would end up with but I'm not sure how we can get that data other than trying to have a survey later on. Not sure current Applications will give us a good point of reference for this design. 
Another thing is that potentially if one uses a lot of folders, then there isn't that many icons left inside the home folder so that would potentially decrease the number of rows in the app-icons part.

**Comment by WatchMkr** [comment]
Limit the total possible folders to the number that fits in two rows.

App icons scroll vertically as they are now.

This design feels pretty good for touch though it gives me the feeling we'll need to switch to natural scrolling by default at some point.

**Comment by maria-komarova** [comment]
I didn't mean app icons need to scroll any different, to clarify just in case.

Switching to natural scrolling by default might be a good idea, I believe I've heard a few comments from the users about that at various points in time.

**Comment by ahoneybun** [comment]
Having the popup in the middle of the screen seems odd since you have to click the Applications button on the top left of the screen. I understand that most of us would do Super+A I think others would click the button.

**Comment by maria-komarova** [comment]
It should show up at the top of the screen actually. There would be some traveling distance on regular displays but it won't be too bad. Ultrawide displays could be the ones where traveling distance with the mouse might feel too far. But maybe we can later think of the options for other placement of the popup for the specific display sizes.

**Comment by WatchMkr** [comment]
@ahoneybun some people use Applications in the top bar. Some use the icon in the dock. Others use the keyboard shortcut. Then there's touchpad gestures and next there will be a touchscreen gesture. Like the Launcher and Workspaces, the App Library isn't physically attached to a method of initializing it.

**Comment by WatchMkr** [comment]
One more
- Make applications and folders listings alphabetical

**Comment by jackpot51** [comment]
Super+A doesn't close the window after it opens

**Comment by jackpot51** [comment]
What should we do with text wrapping of application names? Right now, if they are too long, hovering will show the whole name but move things around

**Comment by maria-komarova** [comment]
Showing full name on hover is fine with me but things shouldn't move around then. Hopefully, with the larger spacing between the rows, we should have space for two lines without the need to push anything to move.

**Comment by ahoneybun** [comment]
> One more
> 
>     * Make applications and folders listings alphabetical

I dislike that GNOME's default application list doesn't allow this. I love that I can move applications around but having both options would be awesome.

**Comment by ahoneybun** [comment]
This is what mine looks like currently. 

ksnip_20211104-092308

My display is at 1920x1080 100% Scale.

**Comment by maria-komarova** [comment]
One more thing, The folder should get into the focused state when one drags the app icon and hovers over the folder so that it is clear this is the drop target. Here is the styling from the mockups in Figma (orange overlay and thin orange border):
State=Drop-Target, Size=Default, Type=Default, Appearance=Dark

**Comment by ids1024** [comment]
> having both options would be awesome.

Supporting both presents some complications. There would probably need to be a way to switch between the two modes. The Icons in stock Gnome are stored by page,  so we'd probably need to store the order somewhere other than the stock Gnome gsettings key. If you install a new app, does it go to the end of the list?

And I'm not sure how the usability would be, dragging icons around a scrolled flowbox.

What I'd personally like is a mode to just sort by category, instead of having folders. Might not be too hard to add.

> This is what mine looks like currently.
> My display is at 1920x1080 100% Scale.

I wasn't sure how to size it, so initially I just hard coded a size that looked good on my 1440p monitor, then when I tried it at 1080p, I added code to clamp the size to be no larger than the screen.

Clearly not the best solution, though it works. I'm not sure what the ideal size for the dialog would be.

**Comment by WatchMkr** [comment]
Adjusting the icon sizes, padding and limiting to three rows of icons should get us to the right window size and ratio. The design is intended to change in vertical views but perhaps that's something we can hold off on. I updated the original issue with the correct mockup and prototype links. Hopefully that helps.

Mockups: https://www.figma.com/file/SpjW7ksxjSfXxHmKROdwb3/Application-Library
Prototype: https://www.figma.com/proto/SpjW7ksxjSfXxHmKROdwb3/Application-Library?node-id=268%3A1288&scaling=scale-down&page-id=268%3A1180&starting-point-node-id=268%3A1288&show-proto-sidebar=1

We only plan to offer alphabetical sorting. I just don't see manual making sense in this design or adding value.

**Comment by ahoneybun** [comment]
Are there plans to allow folders to be moved around or is the end goal going to be categories?

**Comment by WatchMkr** [comment]
The folders will be alphabetical. Categories aren't planned. Custom folders provide the option to group by categories or custom groupings whereas categories alone are rigid.

**Review by jackpot51 — APPROVED** [review]

**Review by leviport — APPROVED** [review]
I'm seeing a few small bugs, but I think this works well enough to be released on the 21.10 beta. We can address those bugs with separate PRs.

**Pull request merged**
